Demo/Areas/Admin/Controllers/CategoryController.cs
using Demo.Areas.Admin.Models;
using Demo.DAL.Services;
using Demo.Mapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.Areas.Admin.Controllers
{
    public class CategoryController : Controller
    {
        public ActionResult Index()
        {
            CategoryService service = new CategoryService();
            IEnumerable<CategoryModel> model = service.GetAll()
                .Select(item => item.Map<CategoryModel>());
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            CategoryService service = new CategoryService();
            service.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Demo/Controllers/DefaultController.cs
using Demo.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Demo.Controllers
{
    public class DefaultController : Controller
    {
        public ActionResult Home()
        {
            // objet dynamic ie: possède des propriétés definies à la volée
            // que l'on va pouvoir utiliser dans les vues
            // TempData tableau qui contient des données partagées entre les actions et le controlleurs
            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View();
        }

        [HttpGet]
        public ActionResult Contact()
        {
            return View(new ContactFormModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contact(ContactFormModel model)
        {
            if (ModelState.IsValid)
            {
                #region To Do if form is valid
                //on instancie un MailMessage qui contiendra les infos de l'email que l'on souhaite envoyer
                MailMessage message = new MailMessage();
                // on instancie un service qui va envoyer les emails pour nous
                SmtpClient client = new SmtpClient(
                    ConfigurationManager.AppSettings["SMTPServer"]
                );
                // on spécifie les informations de l'email
                message.To.Add(ConfigurationManager.AppSettings["AdminMail"]);
                message.From = new MailAddress(model.AuthorEmail);
                message.Subject = model.Object;
                // on va envoyer un email en html
                message.IsBodyHtml = true;
                message.Body
                    = $"<p>Auteur: {model.AuthorEmail}</p><p>Contenu: {model.Content}</p>";
                // on spécifie la configuration de notre client mail
                client.EnableSsl = true;
                client.Port
                    = int.Parse(ConfigurationManager.AppSettings["SMTPPort"]);
                client.Credentials = new NetworkCredential(
                    ConfigurationManager.AppSettings["SMTPUser"],
                    ConfigurationManager.AppSettings["SMTPPwd"]
                );

                //on envoie l'email
                client.Send(message);

                // TempData ne doit être utilisé que dans le cas d'une redirection
                // sinon utiliser directement le ViewBag
                TempData["SuccessMessage"] = "Votre email a bien été envoyé";

                //rediriger vers la page d'accueil
                return RedirectToAction("Home"); 
                #endregion
            }
            ViewBag.ErrorMessage = "Le formulaire n'est pas valide";
            return View(model);
        }

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }

        public ActionResult Order()
        {
            return View();
        }
    }
}

Demo/Controllers/DishController.cs
using Demo.DAL.Entities;
using Demo.DAL.Services;
using Demo.Mapper;
using Demo.Models;
using Demo.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.Controllers
{
    public class DishController : Controller
    {
        // GET: Dish
        public ActionResult Index()
        {
            // récupération d'un dish en utilisant un service de la DAL
            DishService dishService = new DishService();
            // on récupère une liste d'objets de la DAL 
            IEnumerable<Dish> collection = dishService.GetAll();
            // on transforme ces objets en objet en type model
            //List<DishDetailsModel> model = new List<DishDetailsModel>();
            //foreach(Dish d in collection)
            //{
            //    model.Add(d.Map<DishDetailsModel>());
            //}
            IEnumerable<DishDetailsModel> model = collection
                .Select(item => item.Map<DishDetailsModel>());

            return View(model); // je passe le nom de la vue
        }

        public ActionResult Details(int id)
        {
            // On instancie un DishService
            // Son rôle est de récupérer ou de modifier des infos dans la table Dish
            DishService dishService = new DishService();
            DishDetailsModel model = dishService
                .Get(id).Map<DishDetailsModel>();

            //// On mappe l'entité db en model de présentaion
            //DishDetailsModel model = new DishDetailsModel
            //{
            //    Id = dish.Id,
            //    Name = dish.Name,
            //    Price = dish.Price,
            //    CategoryId = dish.CategoryId,
            //    Discount = dish.Discount,
            //    Picture = dish.Picture
            //};

            // Génération de la vue et passage du model à la vue
            return View(model);
        }

        [CustomSecurity("Customer", "ADMIN")]
        public ActionResult Cart()
        {
            return View();
        }

        public ActionResult Search()
        {
            return View(new SearchFormModel());
        }

        [HttpPost]
        public ActionResult AjaxSearch(SearchFormModel model)
        {
            //récupérer tous les plats
            DishService service = new DishService();
            IEnumerable<Dish> allDishes = service.GetAll();

            //fitre les plats en fonction des critères du formulaire
            IEnumerable<DishDetailsModel> results = allDishes.Where(
                    d => d.Name.ToLower().Contains(model.NameSushi?.ToLower() ?? string.Empty)
            //transforme les "Dish" en "DishDetailsModel"
            ).Select(d => d.Map<DishDetailsModel>());
            if(model.PickedCategories != null)
            {
                results
                    = results.Where(d => model.PickedCategories.Contains(d.CategoryId));
            }
            return PartialView(results);
        }
    }
}

Demo/Controllers/SecurityController.cs
using Demo.DAL.Entities;
using Demo.DAL.Services;
using Demo.Mapper;
using Demo.Models;
using Demo.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.Controllers
{
    public class SecurityController : Controller
    {
        [HttpGet]
        public ActionResult Register()
        {
            return View(new RegisterFormModel());
        }

        [HttpPost]
        public ActionResult Register(RegisterFormModel model)
        {
            if (ModelState.IsValid)
            {
                // TODO Insérer dans la db
                UserService service = new UserService();
                service.Insert(model.Map<User>());
                // TODO Afficher un message de success
                TempData["SuccessMessage"] = "Votre inscription ...";
                // TODO Rediriger qque part
                return RedirectToAction("Home", "Default");
            }
            // TODO Afficher un message d'erreur
            ViewBag.ErrorMessage = "...";
            return View(model);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View(new LoginFormModel());
        }

        [HttpPost]
        public ActionResult Login(LoginFormModel model)
        {
            if (ModelState.IsValid)
            {
                // Connection au UserService et Récupération d'un user connecté
                UserService service = new UserService();
                User connectedUser = service.Login(model.Email, model.Password);
                // si user != null
                if(connectedUser != null)
                {
                    // Enregistrer l'utilisateur dans une session
                    Utils.Session.Instance.IsLogged = true;
                    Utils.Session.Instance.ConnectedUser = connectedUser;
                    // Redirection + message de bienvenue
                    TempData["SuccessMessage"] = "Bienvenue";
                    return RedirectToAction("Home", "Default");
                }
                // Sinon
                // Afficher Message d'erreur et Vue
                ViewBag.ErrorMessage = "Votre mot de passe ou votre email est incorrect";
                return View(model);
            }
            // Afficher un message d'erreur
            ViewBag.ErrorMessage = "Le formulaire n'a pas bien été rempli";
            return View(model);
        }

        public ActionResult Logout()
        {
            Utils.Session.Instance.Logout();
            TempData["SuccessMessage"] = "Au revoir";
            return RedirectToAction("Home", "Default");
        }
    }
}

Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sushi Shop", "Home", "Default", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Home", "Default")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Default")</li>
                    <li>@Html.ActionLink("Menu", "Index", "Dish")</li>
                    @{
                        if (!Demo.Utils.Session.Instance.IsLogged)
                        {
                            <li>@Html.ActionLink("S'enregistrer", "Register", "Security")</li>
                            <li>@Html.ActionLink("Se Connecter", "Login", "Security")</li>
                        }
                        else
                        {

                            <li>@Html.ActionLink("Panier", "Cart", "Dish")</li>
                            <li>@Html.ActionLink("Se Déconnecter", "Logout", "Security")</li>
                            if(Demo.Utils.Session.Instance.ConnectedUser.Role == "ADMIN")
                            {
                                <li>@Html.ActionLink("Administration", "Index", "Category", new { Area = "Admin" }, null)</li>
                            }
                        }
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div style="margin-top:30px">
            @if (ViewBag.SuccessMessage != null)
            {
                <div class="alert alert-success">
                    <p>@ViewBag.SuccessMessage</p>
                </div>
            }
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="alert alert-danger">
                    <p>@ViewBag.ErrorMessage</p>
                </div>
            }
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Demo/Views/Shared/_OtherLayout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <h1>Ma super Entête</h1>
    <p>Mon Autre Layout</p>

    @RenderBody()
    <h1>Mon Super Footer</h1>
</body>
</html>